### ISSUE TITLE
Composer Error V2

### ISSUE THREAD

**Issue by thefubon** [ryssbowh/craft-themes#1]
Craft CMS - 3.6.2

Linker output: Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- ryssbowh / craft-theme-installer-plugin [1.0.0, ..., 1.0.1] require composer-plugin-api ^ 1.0 -> found composer-plugin-api [2.0.0] but it does not match the constraint.
- ryssbowh / craft-themes 1.0.0 requires ryssbowh / craft-theme-installer-plugin ^ 1.0 -> satisfiable by ryssbowh / craft-theme-installer-plugin [1.0.0, 1.0.1].
- Root composer.json requires ryssbowh / craft-themes 1.0.0 -> satisfiable by ryssbowh / craft-themes [1.0.0].

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

**Comment by ryssbowh** [comment]
Fixed in 1.0.1

**Comment by thefubon** [comment]
COOOOL
