### ISSUE TITLE
Wrong css file url when craft is installed in subdirectory

### ISSUE THREAD

**Issue by piotrpog** [ryssbowh/craft-themes#10]
**Describe the bug**
My craft install URL is for example `http://localhost/subdirectory/web`, while plugin uses `http://localhost/themes/bootstrap-theme/app.36e1520e.css?v=1654870907` address for css file.

**Versions**
Craft: Craft Solo 4.0.4
Themes: 4.1.5
PHP: 8.1.2
Database: MySQL 5.5.5

**Comment by ryssbowh** [comment]
I added a setting on the bootstrap theme `scssBaseUrl` to handle this situation, this is out on 2.0.3.
In your case you would set it to  `/subdirectory/web/themes/bootstrap-theme`

**Comment by piotrpog** [comment]
Wouldnt it be better to just use alias of `@web` when calculating css file URL? Then file path would be correct without using any additional settings.

**Comment by ryssbowh** [comment]
Yeah you're right, it can be calculated from @themeWeb, done in 2.0.4
