### ISSUE TITLE
Displaying theme files in control panel and which ones are overwritten by current templates

### ISSUE THREAD

**Issue by piotrpog** [ryssbowh/craft-themes#12]
Some time ago i was playing around with idea of creating themes plugin and i created some simple functionality showing theme files. FIles were displayed in "tree" format and these that were overwritten by current templates were marked. Here's how it looked like (red ones are overwritten):

![image](https://user-images.githubusercontent.com/42622545/173226648-b8a92735-69ea-42f7-b40b-5be16411b624.png)

If you want, i can make PR with that.

**Comment by ryssbowh** [comment]
That's a good idea, I thought about it too.
How useful would it be to know that though ?
The way I see it, it would be useful if you're updating to a new version of the themes plugin, and you need to know which templates have been changed in that version, but then it becomes more complicated.
Also comes the problem of the templates that partially override other templates, example for the pro version, `layout/category.twig` would overwrite `layout.twig` even if you've not overridden `layout.twig`, would that need to show then ?

**Comment by piotrpog** [comment]
Well for me it would just be good to know which fules in my child theme are "oryginal" and which one are overwriting something in parent theme.

"Also comes the problem of the templates that partially override other templates, example for the pro version, layout/category.twig would overwrite layout.twig even if you've not overridden layout.twig, would that need to show then ?"

Not sure i get it (still learning about details of plugin), with `layout/category.twig`, `layout` would be directory, but it would overwrite `layout.twig` file in child theme?

Can you link me to specific documentation fragment about that?

**Comment by ryssbowh** [comment]
Here's the documentation : https://github.com/ryssbowh/craft-themes/wiki/Developers#templating-pro

Themes can override `layouts/category.twig` and **not** override `layouts/layout.twig` (I mentionned the wrong path in my previous message), in which case only pages associated with categories will use that template.
And that's the same idea for entries, tags, volumes, globals, regions, blocks, displayers, groups etc.
I guess all those can be checked too.

I'll try something, will probably only show the templates that are overridden as there could be hundreds of available templates on a big website.

**Comment by ryssbowh** [comment]
Hi, this is now on 3.3.0 and 4.2.0 as a new utility entry.

It will list all overridden system templates, and actual file templates overridden for each theme.
