### ISSUE TITLE
How do I overwrite theme template file?

### ISSUE THREAD

**Issue by piotrpog** [ryssbowh/craft-themes#13]
Maybe i am doing something wrong. 
I have clean install of themes plugin and bootstrap theme. I set bootstrat theme as default theme in plugin settings. I created single entry channel and set its template as `themed_page`. Page correctly shows bootstrap theme on frontend.

Then i created `themes` directory in main Craft directory and put my own `themed_page` here - `themes/themed_page,twig`. I also tried creating subdirectory `front` here, so my file was `themes/front/themed_page.twig`. But still, oryginal `themed_page.twig` was used as template, not one i created.

**Comment by ryssbowh** [comment]
@piotrpog creating a theme folder won't be enough, you'll need to create a theme and install it as any other plugin.
The command `craft themes/create/theme name` can do most of the work for you. This would create the theme in the `themes` folder by default, the name of the folder can be changed in the command options, see `craft help themes/create/theme`

**Comment by piotrpog** [comment]
@ryssbowh 
This creates new empty theme, but does not take care of extending parent theme/inheritance. 

In docs i found "Themes can extend each other with the method getExtends(): string of their main class." Can you provide example, how would that work with theme extending bootstrap theme?

**Comment by ryssbowh** [comment]
Your main plugin/theme class can define the getExtends() method :
```
public function getExtends(): ?string
{
    return 'bootstrap-theme';
}
```
