### ISSUE TITLE
"Error while fetching the theme's templates" - in rules/theme rules page

### ISSUE THREAD

**Issue by piotrpog** [ryssbowh/craft-themes#15]
I installed bootstrap theme using composer and set it as default in theming/rules/default theme. Then i set entry template as `themed_page`. When i enter entry page, bootstrap template shows correctly.
Then in my `templates` directory, i created my own `themed_page` file. It overwrites bootstrap theme when i enter entry page.
I assumed that i would see that it is overwritten in rules/theme rules page - but instead this page shows "Error while fetching the theme's templates" error.
It also shows when my `templates` directory is empty.

**Comment by ryssbowh** [comment]
Hi,

Please use the template provided to report issues, I can't replicate this without clear steps or knowing which versions of Craft/Themes plugin you're using

**Comment by piotrpog** [comment]
Would that be enough?

**Versions**
Craft:  4.2.3
Themes: 4.2.3
PHP: 8.1.2
Database: MySQL 5.5.5

Bootstrap theme:  2.0.5

**Comment by ryssbowh** [comment]
Yes that helps.
Then what did you do exactly ?
- set entry template as themed_page
- Then in my templates directory, i created my own themed_page file. Which templates directory ? Of your own theme ? or the root one ?

> but instead this page shows "Error while fetching the theme's templates" error.

Where did that happen ?

**Comment by piotrpog** [comment]
I think i know what the problem is. Overwritten templates are requested as ajax request. And this request goes to wrong url, it does not take into account if website is in subdirectory on server. In my case it lways requests:
`http://localhost/?action=themes/cp-themes/overridden-templates`

**Comment by ryssbowh** [comment]
I see,
This should be fixed in 4.2.4 and 3.3.2
