### ISSUE TITLE
Content block - no settings

### ISSUE THREAD

**Issue by piotrpog** [ryssbowh/craft-themes#17]
I added "content" block to one of regions of bootstrap theme. I assumed this would be block which we can place some rich text in, but it seems that there is no any field for that in block settings:

![image](https://user-images.githubusercontent.com/42622545/188285730-baaca7f9-ab9b-460b-8810-aad4ce1818ab.png)

**Comment by piotrpog** [comment]
Now that i took a closer look, i think content is where fields and properties like title are outputted.

**Comment by ryssbowh** [comment]
Yes, the content block outputs the displayers for whichever entry/category is visited
