### ISSUE TITLE
Accordion displayer for "author" property - error when saving

### ISSUE THREAD

**Issue by piotrpog** [ryssbowh/craft-themes#18]
When i try to set accordion displayer for "author" property for entry, i get error:

```
Getting unknown property: Ryssbowh\BootstrapTheme\models\fieldDisplayerOptions\UserAccordionOptions::headerDisplays
```

This are settings i try to use:

![image](https://user-images.githubusercontent.com/42622545/188309857-a518e28e-ef9e-4a05-a9d1-1dcfec1e9c7c.png)

**Comment by ryssbowh** [comment]
This has been fixed in Bootstrap theme 1.0.6 and 2.0.5
