### ISSUE TITLE
Displayer settings - using "card" for "author" - why are some properties hidden?

### ISSUE THREAD

**Issue by piotrpog** [ryssbowh/craft-themes#20]
This are settings for "card" displayer, for "author" property.

![image](https://user-images.githubusercontent.com/42622545/188309983-da9a743b-8bef-4cdb-b34d-eacfd0c78be7.png)

Why are properties like "username" set to hidden?

**Comment by ryssbowh** [comment]
Because on the View mode you have selected "Default", they are hidden

**Comment by piotrpog** [comment]
Yes, but why? Where is this defined which of these attributes are hidden?

**Comment by ryssbowh** [comment]
On the user displays, for the default view mode.

If you edit the user displays for that view mode, you'll see that those fields (username, date updated etc) are hidden
