### ISSUE TITLE
Change view mode of entry properties displayed in "content" block

### ISSUE THREAD

**Issue by piotrpog** [ryssbowh/craft-themes#21]
I can set view mode for things like "entries" block. But there is no such option for "content" block - block which displays content of currently viewed element (like `entry` variable in the template). 

Content block has only "active" and "caching" options, no display mode option.

**Comment by ryssbowh** [comment]
As per documentation, the view mode for such elements is always the default one

**Comment by piotrpog** [comment]
Would be useful if we could change that. Would you consider adding such option?

**Comment by ryssbowh** [comment]
I'll think about it, but on a first thought I don't see the use case.

If you need to change how the default view mode looks like you can. I see this default view mode as the "full" version of an entry/category that will be loaded when you load such a page. Then if you need different view modes for other parts of the website you can create them.

**Comment by piotrpog** [comment]
Well, if we can have multiple layouts, with different blocks (content block being one of them), so maybe user would like to "full" version in layout in one way, and in other layout in another way.

**Comment by ryssbowh** [comment]
Of course, but you can already do that. Your default view mode could be anything you want
