### ISSUE TITLE
Nothing happens when i click on left menu in block manager

### ISSUE THREAD

**Issue by piotrpog** [ryssbowh/craft-themes#7]
I installed default bootstrap theme. Not sure if i am doing something wrong, but when i click on blocks in menu on the left (on screenshot below) or try to drag them, nothing happens. My craft version is  4.0.3.

![image](https://user-images.githubusercontent.com/42622545/170839754-077e7d47-d686-4988-8322-9a524430c954.png)

**Comment by ryssbowh** [comment]
Clicking on them wouldn't do anything, they are meant to be drag and  dropped, does that not work ?
What are your versions ? PHP, Themes, Browser

**Comment by piotrpog** [comment]
I misundestood, i thought that these positions can be sorted, not drag and dropped.
