### ISSUE TITLE
Bootstrap theme -  Couldn’t save theme rules

### ISSUE THREAD

**Issue by piotrpog** [ryssbowh/craft-themes#8]
**Describe the bug**
I installed themes plugin and bootstrap theme plugin on clean Craft instance. When i go to rules and try to set bootstrap as default theme, i get "Couldn’t save theme rules" error.

**Versions**
Craft: Craft Solo 4.0.4
Themes: 4.1.5
PHP: 8.1.2
Database: MySQL 5.5.5

**Comment by piotrpog** [comment]
Just realized that it was due to missing `themes` directory. Maybe there should be some warning?

**Comment by ryssbowh** [comment]
Yes that is quite misleading, I removed the validation for the folder on 4.1.6
