### ISSUE TITLE
Bootstrap theme - error when disabling and enabling plugin

### ISSUE THREAD

**Issue by piotrpog** [ryssbowh/craft-themes#9]
**Describe the bug**
When i disable and try to enable agin bootstrap theme, i get this error:

```
Declaration of Ryssbowh\CraftThemes\jobs\ReinstallLayoutsJob::getDescription() must be compatible with craft\queue\BaseJob::getDescription(): ?string
```

**Versions**
Craft: Craft Solo 4.0.4
Themes: 4.1.5
PHP: 8.1.2
Database: MySQL 5.5.5

**Comment by ryssbowh** [comment]
Thanks for reporting, that's fixed in 4.1.6
